server:
  port: 8080
  servlet:
    context_path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://yysahqkgvackob:91e1e6d3d71ef77721b69f334d43d4ce30e2fcc2b00bbc6512381c635b933cc3@ec2-54-163-97-228.compute-1.amazonaws.com:5432/d57m1286d77fbp
    username: yysahqkgvackob
    password: 91e1e6d3d71ef77721b69f334d43d4ce30e2fcc2b00bbc6512381c635b933cc3
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander